const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Plugins.GD_SDK,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{GameTittle: 0},
	{Flash: 0},
	{ButtonPlay: 0},
	{BackButton: 0},
	{LiteTween: 0},
	{MenuCash: 0},
	{MenuIconBitcoin: 0},
	{MenuTittleCoin: 0},
	{Sine2: 0},
	{MenuTittlePick: 0},
	{ReplayButton: 0},
	{MenuParticles: 0},
	{GameCompleteBackground: 0},
	{Rotate: 0},
	{SpinnerLight: 0},
	{MenuTittlePick2: 0},
	{Tween: 0},
	{Pin: 0},
	{B1Button: 0},
	{Item1Level: 0},
	{Item1Price: 0},
	{B2Button: 0},
	{Item2Level: 0},
	{Item2Price: 0},
	{Fade: 0},
	{B3Button: 0},
	{Item3Level: 0},
	{Item3Price: 0},
	{Pin2: 0},
	{B4Button: 0},
	{Item4Level: 0},
	{Item4Price: 0},
	{B5Button: 0},
	{Item5Level: 0},
	{Item5Price: 0},
	{Item6Level: 0},
	{Item6Price: 0},
	{Item7Level: 0},
	{Item7Price: 0},
	{Item8Level: 0},
	{Item8Price: 0},
	{Item9Level: 0},
	{Item9Price: 0},
	{Item10Level: 0},
	{Item10Price: 0},
	{MainBackground: 0},
	{MainPopsicle: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{MainBitcoinReward: 0},
	{Autoclicker: 0},
	{ComboBar: 0},
	{BitsPerSecondBackground: 0},
	{BitsSecond: 0},
	{BonusCoin: 0},
	{BonusReward: 0},
	{GameplayCloudBackground: 0},
	{LightEffect2: 0},
	{MainScoreUI: 0},
	{MainText: 0},
	{MultiplierBackground: 0},
	{MultiplierLines: 0},
	{Progressbar: 0},
	{ProgressFinish: 0},
	{ProgressLines: 0},
	{RewardFont: 0},
	{ShopBackground: 0},
	{ShopForegroundSlide: 0},
	{Slider: 0},
	{SliderBackground: 0},
	{SliderLines: 0},
	{Tutorial1: 0},
	{Tutorial1Hand: 0},
	{Tutorial2: 0},
	{Tutorial2Hand: 0},
	{Tutorial3: 0},
	{Tutorial3Hand: 0},
	{UpgradeUI: 0},
	{VfxCoin: 0},
	{ComboCount: 0},
	{SavingText: 0},
	{ButtonHomeGame: 0},
	{ButtonSave: 0},
	{ButtonSound: 0},
	{Rewardbtn: 0},
	{B6Button: 0},
	{B7Button: 0},
	{B8Button: 0},
	{B9Button: 0},
	{B10Button: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{k10bk: 0},
	{forek10: 0},
	{k10logo: 0},
	{kloading: 0},
	{GameDistributionSDK: 0},
	{char4: 0},
	{Lock4: 0},
	{char2: 0},
	{Lock2: 0},
	{char3: 0},
	{Lock3: 0},
	{char5: 0},
	{Lock5: 0},
	{char6: 0},
	{Lock6: 0},
	{char7: 0},
	{Lock7: 0},
	{char8: 0},
	{Lock8: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite: 0},
	{DragDrop: 0},
	{Swipe: 0},
	{n1: 0},
	{n2: 0},
	{n3: 0},
	{n4: 0},
	{n5: 0},
	{n6: 0},
	{n7: 0},
	{n8: 0},
	{n9: 0},
	{n10: 0},
	{Toucher: 0},
	{Sprite5: 0},
	{buttons: 0},
	{Numbers: 0},
	{GlobalBitcoins: 0},
	{ClickValueBitcoin: 0},
	{ClickSeconds: 0},
	{BitcoinsPS: 0},
	{BitcoinPointsMultiply: 0},
	{ProgressCost: 0},
	{GameProgress: 0},
	{B1Value: 0},
	{B1level: 0},
	{B1Cost: 0},
	{B1bitcoinBoostPS: 0},
	{B2Value: 0},
	{B2level: 0},
	{B2Cost: 0},
	{B2bitcoinBoostPS: 0},
	{B3Value: 0},
	{B3level: 0},
	{B3Cost: 0},
	{B3bitcoinBoostPS: 0},
	{B4Value: 0},
	{B4level: 0},
	{B4Cost: 0},
	{B4bitcoinBoostPS: 0},
	{B5Value: 0},
	{B5level: 0},
	{B5Cost: 0},
	{B5bitcoinBoostPS: 0},
	{B6Value: 0},
	{B6level: 0},
	{B6Cost: 0},
	{B6bitcoinBoostPS: 0},
	{B7Value: 0},
	{B7level: 0},
	{B7Cost: 0},
	{B7bitcoinBoostPS: 0},
	{B8Value: 0},
	{B8level: 0},
	{B8Cost: 0},
	{B8bitcoinBoostPS: 0},
	{B9Value: 0},
	{B9level: 0},
	{B9Cost: 0},
	{B9bitcoinBoostPS: 0},
	{B10Value: 0},
	{B10level: 0},
	{B10Cost: 0},
	{B10bitcoinBoostPS: 0},
	{B2Avalaible: 0},
	{B3Avalaible: 0},
	{B4Avalaible: 0},
	{B5Avalaible: 0},
	{B6Avalaible: 0},
	{B7Avalaible: 0},
	{B8Avalaible: 0},
	{B9Avalaible: 0},
	{B10Avalaible: 0},
	{isEndgame: 0},
	{isSave: 0},
	{BTC2Sound: 0},
	{BTC3Sound: 0},
	{BTC4Sound: 0},
	{BTC5Sound: 0},
	{Combo: 0},
	{ComboCounter: 0},
	{Tutorial: 0},
	{CHAR2: 0},
	{CHAR3: 0},
	{CHAR4: 0},
	{CHAR5: 0},
	{CHAR6: 0},
	{CHAR7: 0},
	{CHAR8: 0},
	{REWARDS: 0},
	{isMuted: 0}
];

self.InstanceType = {
	GameTittle: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	MenuCash: class extends self.ISpriteInstance {},
	MenuIconBitcoin: class extends self.ISpriteInstance {},
	MenuTittleCoin: class extends self.ISpriteInstance {},
	MenuTittlePick: class extends self.ISpriteInstance {},
	ReplayButton: class extends self.ISpriteInstance {},
	MenuParticles: class extends self.IParticlesInstance {},
	GameCompleteBackground: class extends self.ISpriteInstance {},
	SpinnerLight: class extends self.ISpriteInstance {},
	MenuTittlePick2: class extends self.ISpriteInstance {},
	B1Button: class extends self.ISpriteInstance {},
	Item1Level: class extends self.ISpriteFontInstance {},
	Item1Price: class extends self.ISpriteFontInstance {},
	B2Button: class extends self.ISpriteInstance {},
	Item2Level: class extends self.ISpriteFontInstance {},
	Item2Price: class extends self.ISpriteFontInstance {},
	B3Button: class extends self.ISpriteInstance {},
	Item3Level: class extends self.ISpriteFontInstance {},
	Item3Price: class extends self.ISpriteFontInstance {},
	B4Button: class extends self.ISpriteInstance {},
	Item4Level: class extends self.ISpriteFontInstance {},
	Item4Price: class extends self.ISpriteFontInstance {},
	B5Button: class extends self.ISpriteInstance {},
	Item5Level: class extends self.ISpriteFontInstance {},
	Item5Price: class extends self.ISpriteFontInstance {},
	Item6Level: class extends self.ISpriteFontInstance {},
	Item6Price: class extends self.ISpriteFontInstance {},
	Item7Level: class extends self.ISpriteFontInstance {},
	Item7Price: class extends self.ISpriteFontInstance {},
	Item8Level: class extends self.ISpriteFontInstance {},
	Item8Price: class extends self.ISpriteFontInstance {},
	Item9Level: class extends self.ISpriteFontInstance {},
	Item9Price: class extends self.ISpriteFontInstance {},
	Item10Level: class extends self.ISpriteFontInstance {},
	Item10Price: class extends self.ISpriteFontInstance {},
	MainBackground: class extends self.ISpriteInstance {},
	MainPopsicle: class extends self.ISpriteInstance {},
	MainBitcoinReward: class extends self.ISpriteInstance {},
	Autoclicker: class extends self.ISpriteInstance {},
	ComboBar: class extends self.ISpriteInstance {},
	BitsPerSecondBackground: class extends self.ISpriteInstance {},
	BitsSecond: class extends self.ISpriteFontInstance {},
	BonusCoin: class extends self.ISpriteInstance {},
	BonusReward: class extends self.ISpriteInstance {},
	GameplayCloudBackground: class extends self.ISpriteInstance {},
	LightEffect2: class extends self.ISpriteInstance {},
	MainScoreUI: class extends self.ISpriteInstance {},
	MainText: class extends self.ISpriteFontInstance {},
	MultiplierBackground: class extends self.ISpriteInstance {},
	MultiplierLines: class extends self.ISpriteInstance {},
	Progressbar: class extends self.ISpriteInstance {},
	ProgressFinish: class extends self.ISpriteInstance {},
	ProgressLines: class extends self.ISpriteInstance {},
	RewardFont: class extends self.ISpriteFontInstance {},
	ShopBackground: class extends self.ISpriteInstance {},
	ShopForegroundSlide: class extends self.ISpriteInstance {},
	Slider: class extends self.ISpriteInstance {},
	SliderBackground: class extends self.ISpriteInstance {},
	SliderLines: class extends self.ISpriteInstance {},
	Tutorial1: class extends self.ISpriteInstance {},
	Tutorial1Hand: class extends self.ISpriteInstance {},
	Tutorial2: class extends self.ISpriteInstance {},
	Tutorial2Hand: class extends self.ISpriteInstance {},
	Tutorial3: class extends self.ISpriteInstance {},
	Tutorial3Hand: class extends self.ISpriteInstance {},
	UpgradeUI: class extends self.ISpriteInstance {},
	VfxCoin: class extends self.ISpriteInstance {},
	ComboCount: class extends self.ISpriteInstance {},
	SavingText: class extends self.ISpriteInstance {},
	ButtonHomeGame: class extends self.ISpriteInstance {},
	ButtonSave: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	Rewardbtn: class extends self.ISpriteInstance {},
	B6Button: class extends self.ISpriteInstance {},
	B7Button: class extends self.ISpriteInstance {},
	B8Button: class extends self.ISpriteInstance {},
	B9Button: class extends self.ISpriteInstance {},
	B10Button: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	k10bk: class extends self.ITiledBackgroundInstance {},
	forek10: class extends self.ISpriteInstance {},
	k10logo: class extends self.ISpriteInstance {},
	kloading: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	char4: class extends self.ISpriteInstance {},
	Lock4: class extends self.ISpriteInstance {},
	char2: class extends self.ISpriteInstance {},
	Lock2: class extends self.ISpriteInstance {},
	char3: class extends self.ISpriteInstance {},
	Lock3: class extends self.ISpriteInstance {},
	char5: class extends self.ISpriteInstance {},
	Lock5: class extends self.ISpriteInstance {},
	char6: class extends self.ISpriteInstance {},
	Lock6: class extends self.ISpriteInstance {},
	char7: class extends self.ISpriteInstance {},
	Lock7: class extends self.ISpriteInstance {},
	char8: class extends self.ISpriteInstance {},
	Lock8: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Swipe: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	n4: class extends self.ISpriteInstance {},
	n5: class extends self.ISpriteInstance {},
	n6: class extends self.ISpriteInstance {},
	n7: class extends self.ISpriteInstance {},
	n8: class extends self.ISpriteInstance {},
	n9: class extends self.ISpriteInstance {},
	n10: class extends self.ISpriteInstance {},
	Toucher: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	Numbers: class extends self.ISpriteInstance {}
}