const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Function,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Behaviors.bound,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.destroy,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.GD_SDK,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.ApplyTorqueToAngle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Bullet: 0},
	{Block: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Sprite4: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Function: 0},
	{Sprite40: 0},
	{Audio: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Browser: 0},
	{Sprite90: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{RotateScreen: 0},
	{Sprite93: 0},
	{Sprite100: 0},
	{Sprite104: 0},
	{LiteTween: 0},
	{Sprite108: 0},
	{Physics: 0},
	{Sine: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite10: 0},
	{Sprite16: 0},
	{Fade: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{LiteTween2: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{BoundToLayout: 0},
	{DragDrop: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{DestroyOutsideLayout: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Pin: 0},
	{Sprite39: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite44: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{TiledBackground: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{rotacion: 0},
	{Rotate: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{Sprite84: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Particles: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Body: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite89: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite99: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Sprite105: 0},
	{Sprite106: 0},
	{numero: 0},
	{Ok1: 0},
	{Ok2: 0},
	{Ok3: 0},
	{Ok4: 0},
	{Ok5: 0},
	{Ok6: 0},
	{Sprite107: 0},
	{mancha8: 0},
	{mancha1: 0},
	{mancha2: 0},
	{mancha3: 0},
	{mancha4: 0},
	{mancha5: 0},
	{mancha6: 0},
	{mancha7: 0},
	{mancha10: 0},
	{mancha9: 0},
	{mancha11: 0},
	{BOTELLA1: 0},
	{BOTELLA9: 0},
	{Sprite122: 0},
	{Sprite123: 0},
	{Sprite124: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{BOTELLA2: 0},
	{BOTELLA3: 0},
	{BOTELLA4: 0},
	{BOTELLA5: 0},
	{BOTELLA6: 0},
	{BOTELLA7: 0},
	{BOTELLA8: 0},
	{BOTELLA10: 0},
	{BOTELLA11: 0},
	{Sprite127: 0},
	{Particles2: 0},
	{Sprite128: 0},
	{Sprite129: 0},
	{aguja1: 0},
	{aguja2: 0},
	{aguja3: 0},
	{aguja4: 0},
	{Sprite113: 0},
	{cros1: 0},
	{cros2: 0},
	{cros3: 0},
	{cros4: 0},
	{Sprite130: 0},
	{Sprite109: 0},
	{Sprite110: 0},
	{obj1: 0},
	{obj2: 0},
	{obj3: 0},
	{obj4: 0},
	{decal1: 0},
	{decal2: 0},
	{decal3: 0},
	{decal4: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Sprite116: 0},
	{P1: 0},
	{P2: 0},
	{P3: 0},
	{P4: 0},
	{P5: 0},
	{P6: 0},
	{P7: 0},
	{P8: 0},
	{P9: 0},
	{move1: 0},
	{move2: 0},
	{move3: 0},
	{move4: 0},
	{move5: 0},
	{move6: 0},
	{move7: 0},
	{move8: 0},
	{move9: 0},
	{Sprite117: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite121: 0},
	{star1: 0},
	{star2: 0},
	{star3: 0},
	{star4: 0},
	{star5: 0},
	{Sprite131: 0},
	{star6: 0},
	{Particles3: 0},
	{Sprite132: 0},
	{Sprite133: 0},
	{Sprite134: 0},
	{Sprite135: 0},
	{Sprite136: 0},
	{Sprite137: 0},
	{BALL1: 0},
	{BALL2: 0},
	{BALL3: 0},
	{BALL4: 0},
	{BALL5: 0},
	{BALL6: 0},
	{BALL7: 0},
	{BALL8: 0},
	{BALL9: 0},
	{BALL10: 0},
	{BALL11: 0},
	{BALL12: 0},
	{Particles4: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{Sprite140: 0},
	{Sprite141: 0},
	{Sprite142: 0},
	{Sprite143: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{Sprite151: 0},
	{Sprite152: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{BALL13: 0},
	{star7: 0},
	{BALL14: 0},
	{Sprite146: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{Sprite158: 0},
	{Sprite159: 0},
	{Sprite160: 0},
	{Sprite161: 0},
	{Particles5: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{Sprite164: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{Sprite168: 0},
	{n1: 0},
	{Sprite170: 0},
	{Sprite171: 0},
	{Sprite172: 0},
	{Sprite173: 0},
	{Sprite174: 0},
	{Sprite175: 0},
	{Sprite176: 0},
	{Sprite230: 0},
	{Sprite177: 0},
	{casa: 0},
	{Sprite178: 0},
	{cloud1: 0},
	{cloud2: 0},
	{Sprite181: 0},
	{L1Play: 0},
	{Sprite180: 0},
	{ScoreFontse: 0},
	{Sprite179: 0},
	{Sprite182: 0},
	{Sprite183: 0},
	{Sprite184: 0},
	{Particles6: 0},
	{Sprite185: 0},
	{Sprite186: 0},
	{n2: 0},
	{n3: 0},
	{n4: 0},
	{n5: 0},
	{n6: 0},
	{n7: 0},
	{n8: 0},
	{n9: 0},
	{hidrant: 0},
	{Sprite187: 0},
	{Sprite169: 0},
	{Sprite188: 0},
	{Sprite189: 0},
	{Sprite190: 0},
	{Sprite191: 0},
	{Sprite192: 0},
	{Sprite193: 0},
	{Sprite194: 0},
	{Sprite195: 0},
	{Sprite196: 0},
	{Sprite197: 0},
	{flow1: 0},
	{flow2: 0},
	{flow3: 0},
	{flow4: 0},
	{flow5: 0},
	{flow6: 0},
	{flow7: 0},
	{flow8: 0},
	{flow9: 0},
	{Sprite198: 0},
	{Sprite199: 0},
	{Sprite200: 0},
	{ScoreFontse2: 0},
	{Sprite201: 0},
	{Sprite202: 0},
	{LocalStorage: 0},
	{GameDistributionSDK: 0},
	{Sprite43: 0},
	{Sprite155: 0},
	{Sprite203: 0},
	{Sprite204: 0},
	{Sprite205: 0},
	{ScoreFontse3: 0},
	{Anchor: 0},
	{rewards: 0},
	{Sprite206: 0},
	{kiztiled: 0},
	{Sprite20kiz: 0},
	{Sprite9kiz: 0},
	{loading: 0},
	{Family1: 0},
	{Family2: 0},
	{Family3: 0},
	{baz1: 0},
	{baz2: 0},
	{baz3: 0},
	{baz4: 0},
	{baz5: 0},
	{baz6: 0},
	{counter: 0},
	{auto: 0},
	{flower: 0},
	{jump: 0},
	{trueno: 0},
	{hijos: 0},
	{ballto6: 0},
	{ballto5: 0},
	{ballto4: 0},
	{ballto3: 0},
	{ballto2: 0},
	{ballto1: 0},
	{touchcount: 0},
	{conejo: 0},
	{varita: 0},
	{puzzle7: 0},
	{puzzle6: 0},
	{puzzle4: 0},
	{puzzle3: 0},
	{puzzle2: 0},
	{puzzle1: 0},
	{body4: 0},
	{body3: 0},
	{body2: 0},
	{body1: 0},
	{rango1: 0},
	{Numeros: 0},
	{num6: 0},
	{num5: 0},
	{num4: 0},
	{num3: 0},
	{num2: 0},
	{num1: 0},
	{plantitas: 0},
	{caida: 0},
	{comida: 0},
	{pinche: 0},
	{drink: 0},
	{Mona: 0},
	{Touches: 0},
	{world: 0},
	{skin: 0},
	{upgrade8: 0},
	{upgrade7: 0},
	{upgrade6: 0},
	{upgrade5: 0},
	{upgrade4: 0},
	{upgrade3: 0},
	{upgrade2: 0},
	{upgrade1: 0},
	{Coins: 0},
	{Highscore: 0},
	{Score: 0},
	{doubleJump: 0},
	{GameOver: 0},
	{StarShield: 0},
	{stomp: 0},
	{Magnet: 0},
	{Big: 0},
	{Jetpack: 0},
	{RandomLevel: 0},
	{Intro: 0},
	{GameStart: 0},
	{GameSpeed: 0},
	{GravityControl: 0},
	{totalclicks: 0},
	{IsScreenRotate: 0},
	{levelselector: 0}
];

self.InstanceType = {
	Block: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Ok1: class extends self.ISpriteInstance {},
	Ok2: class extends self.ISpriteInstance {},
	Ok3: class extends self.ISpriteInstance {},
	Ok4: class extends self.ISpriteInstance {},
	Ok5: class extends self.ISpriteInstance {},
	Ok6: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	mancha8: class extends self.ISpriteInstance {},
	mancha1: class extends self.ISpriteInstance {},
	mancha2: class extends self.ISpriteInstance {},
	mancha3: class extends self.ISpriteInstance {},
	mancha4: class extends self.ISpriteInstance {},
	mancha5: class extends self.ISpriteInstance {},
	mancha6: class extends self.ISpriteInstance {},
	mancha7: class extends self.ISpriteInstance {},
	mancha10: class extends self.ISpriteInstance {},
	mancha9: class extends self.ISpriteInstance {},
	mancha11: class extends self.ISpriteInstance {},
	BOTELLA1: class extends self.ISpriteInstance {},
	BOTELLA9: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	BOTELLA2: class extends self.ISpriteInstance {},
	BOTELLA3: class extends self.ISpriteInstance {},
	BOTELLA4: class extends self.ISpriteInstance {},
	BOTELLA5: class extends self.ISpriteInstance {},
	BOTELLA6: class extends self.ISpriteInstance {},
	BOTELLA7: class extends self.ISpriteInstance {},
	BOTELLA8: class extends self.ISpriteInstance {},
	BOTELLA10: class extends self.ISpriteInstance {},
	BOTELLA11: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	aguja1: class extends self.ISpriteInstance {},
	aguja2: class extends self.ISpriteInstance {},
	aguja3: class extends self.ISpriteInstance {},
	aguja4: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	cros1: class extends self.ISpriteInstance {},
	cros2: class extends self.ISpriteInstance {},
	cros3: class extends self.ISpriteInstance {},
	cros4: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	obj1: class extends self.ISpriteInstance {},
	obj2: class extends self.ISpriteInstance {},
	obj3: class extends self.ISpriteInstance {},
	obj4: class extends self.ISpriteInstance {},
	decal1: class extends self.ISpriteInstance {},
	decal2: class extends self.ISpriteInstance {},
	decal3: class extends self.ISpriteInstance {},
	decal4: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	P1: class extends self.ISpriteInstance {},
	P2: class extends self.ISpriteInstance {},
	P3: class extends self.ISpriteInstance {},
	P4: class extends self.ISpriteInstance {},
	P5: class extends self.ISpriteInstance {},
	P6: class extends self.ISpriteInstance {},
	P7: class extends self.ISpriteInstance {},
	P8: class extends self.ISpriteInstance {},
	P9: class extends self.ISpriteInstance {},
	move1: class extends self.ISpriteInstance {},
	move2: class extends self.ISpriteInstance {},
	move3: class extends self.ISpriteInstance {},
	move4: class extends self.ISpriteInstance {},
	move5: class extends self.ISpriteInstance {},
	move6: class extends self.ISpriteInstance {},
	move7: class extends self.ISpriteInstance {},
	move8: class extends self.ISpriteInstance {},
	move9: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	star1: class extends self.ISpriteInstance {},
	star2: class extends self.ISpriteInstance {},
	star3: class extends self.ISpriteInstance {},
	star4: class extends self.ISpriteInstance {},
	star5: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	star6: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	BALL1: class extends self.ISpriteInstance {},
	BALL2: class extends self.ISpriteInstance {},
	BALL3: class extends self.ISpriteInstance {},
	BALL4: class extends self.ISpriteInstance {},
	BALL5: class extends self.ISpriteInstance {},
	BALL6: class extends self.ISpriteInstance {},
	BALL7: class extends self.ISpriteInstance {},
	BALL8: class extends self.ISpriteInstance {},
	BALL9: class extends self.ISpriteInstance {},
	BALL10: class extends self.ISpriteInstance {},
	BALL11: class extends self.ISpriteInstance {},
	BALL12: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	BALL13: class extends self.ISpriteInstance {},
	star7: class extends self.ISpriteInstance {},
	BALL14: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	Sprite171: class extends self.ISpriteInstance {},
	Sprite172: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Sprite175: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite230: class extends self.ISpriteInstance {},
	Sprite177: class extends self.ISpriteInstance {},
	casa: class extends self.ISpriteInstance {},
	Sprite178: class extends self.ISpriteInstance {},
	cloud1: class extends self.ISpriteInstance {},
	cloud2: class extends self.ISpriteInstance {},
	Sprite181: class extends self.ISpriteInstance {},
	L1Play: class extends self.ISpriteInstance {},
	Sprite180: class extends self.ISpriteInstance {},
	ScoreFontse: class extends self.ISpriteFontInstance {},
	Sprite179: class extends self.ISpriteInstance {},
	Sprite182: class extends self.ISpriteInstance {},
	Sprite183: class extends self.ISpriteInstance {},
	Sprite184: class extends self.ISpriteInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Sprite185: class extends self.ISpriteInstance {},
	Sprite186: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	n4: class extends self.ISpriteInstance {},
	n5: class extends self.ISpriteInstance {},
	n6: class extends self.ISpriteInstance {},
	n7: class extends self.ISpriteInstance {},
	n8: class extends self.ISpriteInstance {},
	n9: class extends self.ISpriteInstance {},
	hidrant: class extends self.ISpriteInstance {},
	Sprite187: class extends self.ISpriteInstance {},
	Sprite169: class extends self.ISpriteInstance {},
	Sprite188: class extends self.ISpriteInstance {},
	Sprite189: class extends self.ISpriteInstance {},
	Sprite190: class extends self.ISpriteInstance {},
	Sprite191: class extends self.ISpriteInstance {},
	Sprite192: class extends self.ISpriteInstance {},
	Sprite193: class extends self.ISpriteInstance {},
	Sprite194: class extends self.ISpriteInstance {},
	Sprite195: class extends self.ISpriteInstance {},
	Sprite196: class extends self.ISpriteInstance {},
	Sprite197: class extends self.ISpriteInstance {},
	flow1: class extends self.ISpriteInstance {},
	flow2: class extends self.ISpriteInstance {},
	flow3: class extends self.ISpriteInstance {},
	flow4: class extends self.ISpriteInstance {},
	flow5: class extends self.ISpriteInstance {},
	flow6: class extends self.ISpriteInstance {},
	flow7: class extends self.ISpriteInstance {},
	flow8: class extends self.ISpriteInstance {},
	flow9: class extends self.ISpriteInstance {},
	Sprite198: class extends self.ISpriteInstance {},
	Sprite199: class extends self.ISpriteInstance {},
	Sprite200: class extends self.ISpriteInstance {},
	ScoreFontse2: class extends self.ISpriteFontInstance {},
	Sprite201: class extends self.ISpriteInstance {},
	Sprite202: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite203: class extends self.ISpriteInstance {},
	Sprite204: class extends self.ISpriteInstance {},
	Sprite205: class extends self.ISpriteInstance {},
	ScoreFontse3: class extends self.ISpriteFontInstance {},
	rewards: class extends self.ISpriteInstance {},
	Sprite206: class extends self.ISpriteInstance {},
	kiztiled: class extends self.ITiledBackgroundInstance {},
	Sprite20kiz: class extends self.ISpriteInstance {},
	Sprite9kiz: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	Family2: class extends self.ISpriteInstance {},
	Family3: class extends self.ISpriteInstance {},
	baz1: class extends self.ISpriteInstance {},
	baz2: class extends self.ISpriteInstance {},
	baz3: class extends self.ISpriteInstance {},
	baz4: class extends self.ISpriteInstance {},
	baz5: class extends self.ISpriteInstance {},
	baz6: class extends self.ISpriteInstance {}
}