const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Timeline,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.LocalStorage,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.GD_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Timeline.Acts.SetTimelinePlaybackRateByTags,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Timeline.Cnds.OnAnyTimelineFinished,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.ScriptsInEvents.списоксобытий1_Event3_Act2,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.GD_SDK.Acts.ShowAd
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{TimelineController: 0},
	{Touch: 0},
	{ScrollTo: 0},
	{Back_1: 0},
	{Back_2: 0},
	{Granny_1_anima: 0},
	{Sapog: 0},
	{Granny_2: 0},
	{Granny_1_anima2: 0},
	{Granny_1_CRY_SWIM: 0},
	{Granny_1_anima3: 0},
	{Sprite: 0},
	{Audio: 0},
	{Anger_granny_1: 0},
	{Anger_2_fast: 0},
	{Grannyu_Anger_MAX: 0},
	{GrannyAnger: 0},
	{GrannyDamage: 0},
	{Key_global_1: 0},
	{Key_global_2: 0},
	{Fade: 0},
	{Sprite2: 0},
	{what_1: 0},
	{Bullet: 0},
	{Ogjects_troww_Center: 0},
	{Solid: 0},
	{Physics: 0},
	{Sprite3: 0},
	{gun_1: 0},
	{Ogjects_spawnONhit: 0},
	{center_up: 0},
	{Particles: 0},
	{ice_1: 0},
	{Sprite6: 0},
	{gun_2: 0},
	{left_up: 0},
	{right_up: 0},
	{gun_3: 0},
	{Ogjects_troww__RIGHT: 0},
	{Ogjects_troww_LEFT: 0},
	{Object_LEFT: 0},
	{Object_RIGHT: 0},
	{Scip_Button_1: 0},
	{Money_main: 0},
	{Browser: 0},
	{Shop_Button_1: 0},
	{Shop_menu_1: 0},
	{weapon_id: 0},
	{Button_guns_shop_1: 0},
	{Button__GUNS: 0},
	{Button_Items: 0},
	{Button_PETS: 0},
	{Button_7: 0},
	{Open: 0},
	{slot: 0},
	{Shop_global_1: 0},
	{item_id: 0},
	{Button_item_1: 0},
	{pet_id: 0},
	{Button_Pet_1: 0},
	{id_gun: 0},
	{GUN_what_1: 0},
	{ItenLeft_what_1: 0},
	{BIGpet_what_1: 0},
	{price: 0},
	{Text_coast_guns: 0},
	{Text_coast_leftsmall_items_1: 0},
	{Text_coast_BIG: 0},
	{Particles2: 0},
	{Shop_Button_2: 0},
	{Shop_Button_3: 0},
	{Shop_Button_4: 0},
	{Button_8: 0},
	{Sprite7: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{ice_2: 0},
	{ice_3: 0},
	{ice_4: 0},
	{ice_5: 0},
	{ice_6: 0},
	{ice_7: 0},
	{ice_8: 0},
	{ice_9: 0},
	{ice_10: 0},
	{ice_11: 0},
	{ice_12: 0},
	{ice_13: 0},
	{ice_14: 0},
	{ice_15: 0},
	{Oblako_Dust: 0},
	{ice_16: 0},
	{ice_17: 0},
	{cry_bullet: 0},
	{WATER_water_anima_cry: 0},
	{ice_18: 0},
	{ice_19: 0},
	{Ogjects_spawnONhit2: 0},
	{ice_20: 0},
	{Rotate: 0},
	{Sine: 0},
	{ice_21: 0},
	{ice_Menu_Button: 0},
	{ice_23: 0},
	{Sprite9: 0},
	{item_shop: 0},
	{item_shop2: 0},
	{item_shop3: 0},
	{Спрайт: 0},
	{Tween: 0},
	{Bonus: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{shop_id: 0},
	{IAP_BUTTON: 0},
	{shopname: 0},
	{IAP_PRICE: 0},
	{LocalStorage: 0},
	{JSON: 0},
	{AJAX: 0},
	{GameDistributionSDK: 0},
	{What_Objects_Throw: 0},
	{Randome_anima_1: 0},
	{Back_MAIN: 0},
	{wait: 0},
	{save_han: 0},
	{isBuy: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Back_1: class extends self.ISpriteInstance {},
	Back_2: class extends self.ISpriteInstance {},
	Granny_1_anima: class extends self.ISpriteInstance {},
	Sapog: class extends self.ISpriteInstance {},
	Granny_2: class extends self.ISpriteInstance {},
	Granny_1_anima2: class extends self.ISpriteInstance {},
	Granny_1_CRY_SWIM: class extends self.ISpriteInstance {},
	Granny_1_anima3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Anger_granny_1: class extends self.ISpriteInstance {},
	Anger_2_fast: class extends self.ISpriteInstance {},
	Key_global_1: class extends self.ISpriteInstance {},
	Key_global_2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Ogjects_troww_Center: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	gun_1: class extends self.ISpriteInstance {},
	Ogjects_spawnONhit: class extends self.ISpriteInstance {},
	center_up: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ice_1: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	gun_2: class extends self.ISpriteInstance {},
	left_up: class extends self.ISpriteInstance {},
	right_up: class extends self.ISpriteInstance {},
	gun_3: class extends self.ISpriteInstance {},
	Ogjects_troww__RIGHT: class extends self.ISpriteInstance {},
	Ogjects_troww_LEFT: class extends self.ISpriteInstance {},
	Object_LEFT: class extends self.ISpriteInstance {},
	Object_RIGHT: class extends self.ISpriteInstance {},
	Scip_Button_1: class extends self.ISpriteInstance {},
	Money_main: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Shop_Button_1: class extends self.ISpriteInstance {},
	Shop_menu_1: class extends self.ISpriteInstance {},
	Button_guns_shop_1: class extends self.ISpriteInstance {},
	Button__GUNS: class extends self.ISpriteInstance {},
	Button_Items: class extends self.ISpriteInstance {},
	Button_PETS: class extends self.ISpriteInstance {},
	Button_7: class extends self.ISpriteInstance {},
	Shop_global_1: class extends self.ISpriteInstance {},
	Button_item_1: class extends self.ISpriteInstance {},
	Button_Pet_1: class extends self.ISpriteInstance {},
	GUN_what_1: class extends self.ISpriteInstance {},
	ItenLeft_what_1: class extends self.ISpriteInstance {},
	BIGpet_what_1: class extends self.ISpriteInstance {},
	Text_coast_guns: class extends self.ITextInstance {},
	Text_coast_leftsmall_items_1: class extends self.ITextInstance {},
	Text_coast_BIG: class extends self.ITextInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Shop_Button_2: class extends self.ISpriteInstance {},
	Shop_Button_3: class extends self.ISpriteInstance {},
	Shop_Button_4: class extends self.ISpriteInstance {},
	Button_8: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	ice_2: class extends self.ISpriteInstance {},
	ice_3: class extends self.ISpriteInstance {},
	ice_4: class extends self.ISpriteInstance {},
	ice_5: class extends self.ISpriteInstance {},
	ice_6: class extends self.ISpriteInstance {},
	ice_7: class extends self.ISpriteInstance {},
	ice_8: class extends self.ISpriteInstance {},
	ice_9: class extends self.ISpriteInstance {},
	ice_10: class extends self.ISpriteInstance {},
	ice_11: class extends self.ISpriteInstance {},
	ice_12: class extends self.ISpriteInstance {},
	ice_13: class extends self.ISpriteInstance {},
	ice_14: class extends self.ISpriteInstance {},
	ice_15: class extends self.ISpriteInstance {},
	Oblako_Dust: class extends self.IParticlesInstance {},
	ice_16: class extends self.ISpriteInstance {},
	ice_17: class extends self.ISpriteInstance {},
	cry_bullet: class extends self.ISpriteInstance {},
	WATER_water_anima_cry: class extends self.ISpriteInstance {},
	ice_18: class extends self.ISpriteInstance {},
	ice_19: class extends self.ISpriteInstance {},
	Ogjects_spawnONhit2: class extends self.ISpriteInstance {},
	ice_20: class extends self.ISpriteInstance {},
	ice_21: class extends self.ISpriteInstance {},
	ice_Menu_Button: class extends self.ISpriteInstance {},
	ice_23: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	item_shop: class extends self.ISpriteInstance {},
	item_shop2: class extends self.ISpriteInstance {},
	item_shop3: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Bonus: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	IAP_BUTTON: class extends self.ISpriteInstance {},
	IAP_PRICE: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	GameDistributionSDK: class extends self.IInstance {}
}